[package]
name = "ev-apple"
version = "0.1.0"
authors = ["Jan Wojcicki <janwojcicki45@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
state = { version = "0.4.1", features = ["tls"] }
crossbeam-channel = "0.4.2"
tokio = { version = "0.2.21", features = ["full"] }
futures = "0.3.5"
